version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "checkReqWithinBounds"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x2j6b2i10l9t"
s3_prefix = "checkReqWithinBounds"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
